### ISSUE TITLE
Zwift docker error: no Documents folder

### ISSUE THREAD

**Issue by dumasl** [netbrain/zwift#1]
Hi,

First of all thank you for you contributions and help trying to give access to zwift for unix users ! 

I have recently tried running the app through one of your docker containers but I always run into this error:

> There was an error accessing to your Documents folder. There was also an error trying to create a Zwift folder on your Desktop as a fall-back. This means Zwift can't save any files. Please contact Zwift Support.

I'm using ubuntu20.04. I've tried `latest` and `1.19.1` docker tags with no success.

Is it possible I'm facing a privilege kind of error here ? I assume I am missing something but can't find what so far. Maybe you will be able to help me resolving this issue.

Thank you for your help.

**Comment by bigbuka** [comment]
Read through this after having the same issue but not sure how to go about achieving this.  What are the exact steps and commands?

**Comment by netbrain** [comment]
https://github.com/netbrain/zwift/issues/9#issue-1446280910
