### ISSUE TITLE
Volume suddenly very high and a bit distorted

### ISSUE THREAD

**Issue by eskimos20** [netbrain/zwift#10]
Hi! 

Not sure what is causing this but everything seems to work fine when logging in to Zwift but sometimes when I start an workout and that screen appear the sound switches to 100%. My volume in the game is set very low (near the bottom). When this happens and I go to settings in zwift the volume is still set to near the bottom, If I then restart zwift it solves itself. It happens very often, about 30-40% of all the workouts.  

Can it be something with wine and zwift ? 

I am running newest Ubuntu Desktop 22:04:1.

And your latest release, I am using your shell script to start and stop.

/Daniel

**Comment by netbrain** [comment]
I really can't help you with pulseaudio issues. But if you don't mind cycling without audio you can simply omit the following.

`-v /run/user/$UID/pulse:/run/user/1000/pulse` 

When running the container.
