### ISSUE TITLE
Feature Request: Adding --net=host to allow for Ethernet/wifi trainers

### ISSUE THREAD

**Issue by nibbles-bytes** [netbrain/zwift#101]
Hello,

I have edited the zwift.sh on my setup to use the host network. This allows you to use a network connected trainer directly without the need for the Zwift Companion app. I was wondering if anyone had ideas on an elegant solution to have it as an option? I'm assuming everyone wouldn't want to run the container on host. But maybe it can be set with a variable? Happy to put in a PR, just wasn't sure what solution direction to go with.

**Comment by netbrain** [comment]
NETWORKING=host zwift.sh should do the trick? 

See the project README

**Comment by nibbles-bytes** [comment]
Ha yes it should, I'll give that a go. Guess I glossed over that before...thanks!
