### ISSUE TITLE
Update not working anymore in GH actions

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#106]
Think it's due to update flag not being forwarded to

gosu user:user /bin/setup_and_run_zwift

@hobeone ☝️

**Comment by hobeone** [comment]
See https://github.com/netbrain/zwift/pull/107

**Comment by netbrain** [comment]
Still something wrong with the gh action. Not sure why it's failing. But I'll look into out when I got the time

**Comment by hobeone** [comment]
Can you run gh actions locally to test them out?  I can try to debug as well if so.

**Comment by netbrain** [comment]
https://github.com/nektos/act

but it's probably easier to try to run the container as it's run with the github action. 
https://github.com/netbrain/zwift/blob/master/.github/workflows/zwift_updater.yaml

**Comment by netbrain** [comment]
But actually, now that im looking it seems that its caused by the script files you updated has not been update in the container. ( https://github.com/netbrain/zwift/blob/master/.github/workflows/zwift_push.yaml )

This yaml is supposed to update the existing container image with latest script files like the entrypoint.sh and stuff. Actually made a note of this in #99.

So we should really fix #99 which in turn would have fixed this issue aswell after your change in #107

**Comment by netbrain** [comment]
Though it doesn't look like it fixed the update routine :face_exhaling: 

https://github.com/netbrain/zwift/actions/runs/8968054365/job/24626741254#step:5:182

Seems like the update flag still isn't being forwarded, and that it just simply runs zwift instead of updating.

**Comment by sHedC** [comment]
Looking into this too as podman is broke so trying to merge better for both docker and podman.

**Comment by sHedC** [comment]
I have done a partial update to here https://github.com/sHedC/zwift but having some issues with persistance and permissions in Podman, working on it.

**Comment by netbrain** [comment]
It's probably working now, closing for now and re-opening if it fails on next release.
