### ISSUE TITLE
The volume zwift-$USER is empty

### ISSUE THREAD

**Issue by MailFranzel** [netbrain/zwift#120]
I installed the new version on Fedora 39 and 40, it runs well on Wayland and X11.
Automatically logging in with my login name and password works. 
Unfortunately the settings are not saved. My zwift-$USER directory remains empty.
If I add a $HOME/ to the entry for my home volume under GENERAL_FLAGS it works:
     -v $HOME/zwift-$USER:/home/user/.wine/drive_c/users/user/Documents/Zwift

is that correct?

greetings Franzel

**Comment by sHedC** [comment]
That is curious it should not be needed as the zwift-$USER is actually stored under .local/share/containers/storage not under home.

Can you see where the zwift directory exists, starting in your home directory:  'find . -name "zwift-$USER" -print 2>/dev/null'
replace $USER with your user id.

**Comment by MailFranzel** [comment]
Thanks for the answer and the information!
I found 2  "zwift-$USER" directories
one under ./.local/share/containers/storage/volumes/
and my "own" ./zwift-martin

The first one is empty :
drwx------. 1 martin martin  24  9. Mai 15:46 .
drwx------. 1 martin martin 248 13. Mai 21:22 ..
drwx------. 1 524288 524288  10  9. Mai 15:46 zwift-martin

I change the owner to martin:martin and with the original 
"-v zwift-$USER:/home/user/.wine/drive_c/users/user/Documents/Zwift"
it is running fine!

**Comment by sHedC** [comment]
Great, it was one of the hang up's from previous versions it would create a volume with re-mapped UID and GID which then could not be written too.  Changing the owner works perfectly, new script should create with the correct owners.
