### ISSUE TITLE
Container exits with errors

### ISSUE THREAD

**Issue by gaeljw** [netbrain/zwift#13]
I'm getting the following output logs when running the container manually, not sure how to troubleshoot :+1: 

```
$ docker run               --rm    --privileged    -e DISPLAY=$DISPLAY     -v /tmp/.X11-unix:/tmp/.X11-unix        -v /run/user/$UID/pulse:/run/user/1000/pulse    -v $ZWIFT_HOME:/home/user/Zwift         $VGA_DEVICE_FLAG      $IMAGE:$VERSION

...

+ echo 'starting zwift...'
+ wine64 start ZwiftLauncher.exe
0050:err:ole:start_rpcss Failed to start RpcSs service
+ wine64 start RunFromProcess-x64.exe ZwiftLauncher.exe ZwiftApp.exe
+ pgrep ZwiftApp.exe
Waiting for zwift to start ...
+ echo 'Waiting for zwift to start ...'
+ sleep 1
0184:err:ole:CoGetContextToken apartment not initialised
+ pgrep ZwiftApp.exe
+ echo 'Killing uneccesary applications'
+ pkill ZwiftLauncher
Killing uneccesary applications
+ pkill MicrosoftEdgeUp
+ pkill ZwiftWindowsCra
```

Any idea in which direction I should look for help?

**Comment by netbrain** [comment]
Exactly what is wrong? Are you referring to the pkill statements? Those are
part of the script to remove uneccesary processes that are spawned by Zwift.

**Comment by gaeljw** [comment]
Look's like wine doesn't run? What I observe is that the container exits after these logs, without more information. No Zwift, no window, nothing. 🤷‍♂️

**Comment by netbrain** [comment]
Can you give me some information about your system? Os, xorg/Wayland?
Graphics card etc..

Also does the process hang? I.e does docker ps show anything after you
start Zwift or does it simply exit by itself?

**Comment by gaeljw** [comment]
Sure, it's a Linux Fedora 36, I believe it's Gnome with Wayland though I'd have to double check. I will also try on a Xorg to troubleshoot.

The process does not hang, the container simply exit by itself.

**Comment by netbrain** [comment]
Too me it sounds like there is an issue in creating the viewport for rendering zwift. So maybe it's a wayland issue, driver issue, or unsupported graphics card?

If you have a nvidia card, you need the nvidia-container-toolkit, for other cards they "should" work by making them accesible through --device /dev/dri.

**Comment by netbrain** [comment]
Also, this looks like an interesting project that this could probably benefit from.

https://github.com/mviereck/x11docker

**Comment by netbrain** [comment]
Yeah most likely the container is missing Wayland support. Feel free to add
it 😊 🙏
