### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by OSLDNKKfEUVTABDLiNgk** [netbrain/zwift#157]
Documentation lists the correct values, but then have a trailing ` zwift` (eg `NETWORKING=host zwift`) that cause bash level 1000 too high errors upon launch. For example, to get Zwift to see a Wahoo Direct Connect adapter, one must add `NETWORKING=host` to this file: `~.config/zwift/config`. A few of the instructions have this issue.

Thank you for packaging Zwift for us. It launches and runs well, and consistently! I'm so glad I didn't need to buy another computer just to run a legacy operating system.

**Comment by netbrain** [comment]
I'm sorry for the confusion, the trailing Zwift is supposed to be there, well, not in the config, but if you run it in terminal.

So. NETWORKING=host is the environment variable declaration and the trailing Zwift is the command to launch.

You could also write this as
```
export NETWORKING=host
zwift
```

In the terminal window mind you.

When you add these config options to the config file instead however, then yes no trailing zwift is required. I'll see if we can't make this crystal clear.
