### ISSUE TITLE
[HELP (Not Launching/ Crashing)] Zwift doesn't start from command line

### ISSUE THREAD

**Issue by hollysheep** [netbrain/zwift#158]
### Checklist

- [X] I have given details of my install including Distribution, Wayland/ XOrg, Parameters Used, echo $XAUTHORITY, etc.
- [X] I have provided logs showing any errors, if available (use `DEBUG=1 zwift`)
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [ ] This issue is not a duplicate issue of previous issue.

### Describe the issue

When i open a Temrinal and try to start zwift with the command "zwift" nothing happens.

### Distribution Details

Xubuntu 22.04

### Reproduction steps

1. installed docker desktop
2. installed zwift
3. i had to add the folder .X11-unix unter docker settings

Then i started zwift and i had to create a docker account. After a restart of my system nothing happens when i run 'zwift'. I don't know if docker desktop is running. When i open it from start menu as i did before nothing happens. Before there was a login screen. When i run "/opt/docker-desktop/bin/docker-desktop" in terminal i get this:

```
[2024-09-18T10:38:58.691918773Z][docker-desktop] running under systemd
```

but systemd could not find docker-desktop:

```
systemctl status docker-desktop
Unit docker-desktop.service could not be found.
```

**Comment by netbrain** [comment]
Try installing docker without desktop

**Comment by netbrain** [comment]
https://github.com/docker/docker-install
