### ISSUE TITLE
[Question] Why this train of thought around xhost?

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#170]
@sHedC , the following doesn't seem to work right on podman. I have recently been experimenting with podman, (always been a docker user) but in my case xhost has to be run in order for podman to be able to draw to the screen.
```
if [ -x "$(command -v xhost)" ] && [ $ZWIFT_UID -ne $(id -u) ] && [ -z $WINE_EXPERIMENTAL_WAYLAND ]; then
    xhost +local:$($CONTAINER_TOOL inspect --format='{{ .Config.Hostname  }}' $CONTAINER)
fi

```

So when manually doing a `xhost +` and then run `zwift` everything works fine.

So my question is, why does all these have to be true in order for xhost to be run in the above if statement? Maybe we should simlpy have the first check, if xhost is on the path, then invoke it.

**Comment by sHedC** [comment]
Sorry, been on workshops and super busy.

Well Xhost is relevant if it exists and we are not running in Wayland mode (with wayland no reason to run xhost).

Podman runs as the user that started it and by default this user is passed through and mapped to the container user.   So the container user should get same access as running user.

If you say to run as a different ID (not your own ID) then xhost is not given as you are mapping the custom ZWIFT_ID to the podman id and have to initiate xhost to allow control.

However I have no idea why you would use a different ZWIFT_ID so most of this was guess work as don't know the use case that this would be needed.

if I have two id's 1001 and 1000 and run zwift from either without giving a ZWIFT_ID this should work but if I run as 1000 and pass through ZWIFT_ID=1001 I need to explicitly give xhost access.

**Comment by netbrain** [comment]
My usecase is that i have a machine with separate users, when the machine boots, it starts greetd service with tuigreet. (a textual login menu) that displays a list of users. All users are passwordless, so they simply choose their user, and are launched into Xorg running openbox, and a xinitrc script that launches zwift.

The xhost issue, is only a problem for the uid that is other than 1000, so for my user, everything works fine. but for other users, zwift simply won't be displayed, even though it's running.

So with this in  mind, and your explanation aswell, it's safe to assume that the [ $ZWIFT_UID -ne $(id -u) ] could be omitted? And that would most likely fix the mentioned issue?

**Comment by sHedC** [comment]
Yes

**Comment by netbrain** [comment]
Fixed in https://github.com/netbrain/zwift/commit/d1c4f8694f1300395e1f2e7133adb093d3c4c0da
