### ISSUE TITLE
[HELP (Not Launching/ Crashing)]

### ISSUE THREAD

**Issue by harlempaul** [netbrain/zwift#171]
### Checklist

- [X] I have given details of my install including Distribution, Wayland/ XOrg, Parameters Used, echo $XAUTHORITY, etc.
- [X] I have provided logs showing any errors, if available (use `DEBUG=1 zwift`)
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of previous issue.

### Describe the issue

I successfully installed docker.

I try to run zwift but I get:
```
$ zwift
You are running latest zwift.sh 👏
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/images/create?fromImage=netbrain%2Fzwift&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Error - Error can't run zwift, check variables!
```

### Distribution Details

linux mint 22
just installed docker
I have an old nvidia card

### Reproduction steps

1. type `zwift`
2. press enter

**Comment by netbrain** [comment]
You are probably not a part of the docker group. You need to add yourself to the docker group.

Can't remember quite what the command is, but something like usermod -aG docker username

**Comment by harlempaul** [comment]
Thanks for the response, I tried:
`$ sudo usermod -aG docker MY_USER_NAME`
logged out, and in again, and tried zwift  command:

```
$ zwift
You are running latest zwift.sh 👏
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/images/create?fromImage=netbrain%2Fzwift&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Error - Error can't run zwift, check variables!
```

**Comment by harlempaul** [comment]
I also see my user name in the group:
<pre>$ grep docker /etc/group
<font color="#EF2929"><b>docker</b></font>:x:999:MY_USER_NAME
</pre>

**Comment by harlempaul** [comment]
I no longer get that error. I will look up the next error  ;-)

**Comment by rollecode** [comment]
I have the same error and I'm part of the docker group.
