### ISSUE TITLE
Downloaded 2.4GB but 21Gb Usage

### ISSUE THREAD

**Issue by tomasmueller** [netbrain/zwift#181]
### Checklist

- [X] I have given details of my install including Distribution, Wayland/ XOrg, Parameters Used, echo $XAUTHORITY, etc.
- [X] I have provided logs showing any errors, if available (use `DEBUG=1 zwift`)
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [ ] This issue is not a duplicate issue of previous issue.

### Describe the issue

After running the command 'zwift' and downloading all files the folder 'containers' in ~/.local/share is using 21GB but only 2.4GB was downloded.

I can't see this when i check the disc usage as a normal user i need sudo for that. Is this normal behaviour?

### Reproduction steps

1. downloading script
2. running 'zwift'
3. check disc usage

**Comment by netbrain** [comment]
You're numbers are probably not correct. The image itself should be somewhere between 5 and 6gb. And when unpacked it should be 10gb+.

You can check this by running 'docker images' command
