### ISSUE TITLE
How can I use this on an ARM machine? 

### ISSUE THREAD

**Issue by fredpeertje** [netbrain/zwift#27]
I tried to run your docker image on an aarch64 Linux Ubuntu 20.04 LTS but get the following error:

The requested image's platform (linux/amd64) does not match the detected host platform (linux/amd64/v8)

How can I use this Docker project on an ARM machine?

**Comment by netbrain** [comment]
You will have to build it the entire thing for arm. This would actually be a good improvement, and would involve the use of matrices in the github actions yaml. Would also probably have to rebuild the wine container aswell.

I'll be happy to take a PR on this, and also help you along the way.

**Comment by netbrain** [comment]
https://github.com/AndreRH/hangover might be of use.

**Comment by netbrain** [comment]
Could be fixed through #28
