### ISSUE TITLE
where is the volume zwift-$USER located?

### ISSUE THREAD

**Issue by MailFranzel** [netbrain/zwift#37]
Thank you very much! A very good and simple description!!
I do not know where the volume zwift-$USER is located, so I changed the line to `-v /home/$USER/zwift-$USER:/home/user/Zwift \`
and I create a directory zwift-franzel in my home directory, now it is working fine for me!

**Comment by netbrain** [comment]
We use named volumes, you should be able to see where it's stored using docker volume list

**Comment by MailFranzel** [comment]
Thanks! I found it !
