### ISSUE TITLE
How to recover a partial ride?

### ISSUE THREAD

**Issue by evesdropper** [netbrain/zwift#39]
Zwift froze midway through a ride, losing my progress; where can I look to find the log files? Thanks!

**Comment by netbrain** [comment]
```
docker volume list

DRIVER    VOLUME NAME
....
local     zwift-netbrain

docker volume inspect zwift-netbrain
[
    {
        "CreatedAt": "2023-09-18T07:41:36+02:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/zwift-netbrain/_data",
        "Name": "zwift-netbrain",
        "Options": null,
        "Scope": "local"
    }
]


sudo ls /var/lib/docker/volumes/zwift-netbrain/_data
```
Or you can mount the volume in a container and do your investigating there:

```
 docker run -it --rm -v zwift-netbrain:/data busybox
 ls /data
```

You need to change your zwift volume name to the format `zwift-$USER` for it to be applicable for your system.

the volume contains a Logs folder which should house your previous ride i guess.
