### ISSUE TITLE
Docker gui not showing with wayland and Fedora 38

### ISSUE THREAD

**Issue by cjensen506** [netbrain/zwift#42]
With Wayland and Fedora 38 the container will start just fine, but the gui never pops up. No obvious error codes or stack trace. When I switch over to x11 everything works just fine. I tried removing the Wayland check and just forcing the `xhost +local` part of the code to run at the end, but issue persists.

Sorry I don't have more details or a solution. Not a blocker for me, but figured I would call it out.

**Comment by netbrain** [comment]
- What graphics card? (nvidia/others)
- What container solution? (docker/podman)
- What command is run to start the container? 
  - i.e p`odman run -d --rm --privileged -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/1000/pulse:/run/user/1000/pulse -v zwift-netbrain:/home/user/Zwift --userns=keep-id --gpus all docker.io/netbrain/zwift:latest`

**Comment by cjensen506** [comment]
Graphics Card: NVIDIA Corporation GP107GLM [Quadro P2000 Mobile] 
Kernel driver in use: nouveau
Container solution: docker (same result with podman though)

Command to start container

`#!/usr/bin/env bash
set -x

# Set the container image to use
IMAGE=${IMAGE:-docker.io/netbrain/zwift}

# The container version
VERSION=${VERSION:-latest}

CONTAINER_TOOL=docker

# Check for updated container image
if [[ ! $DONT_PULL ]]
then
    $CONTAINER_TOOL pull $IMAGE:$VERSION
fi

VGA_DEVICE_FLAG="--device /dev/dri:/dev/dri"


# Start the zwift container
CONTAINER=$($CONTAINER_TOOL run \
    -d \
    --rm \
    --privileged \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /run/user/$UID/pulse:/run/user/1000/pulse \
    -v zwift-$USER:/home/user/Zwift \
    $([ "$CONTAINER_TOOL" = "podman" ] && echo '--userns=keep-id') \
    $VGA_DEVICE_FLAG \
    $IMAGE:$VERSION)

# Allow container to connect to X
xhost +local:$($CONTAINER_TOOL inspect --format='{{ .Config.Hostname  }}' $CONTAINER)
`

**Comment by netbrain** [comment]
could you try to run the following command and see what you get?

```
# podman
podman run -it --rm --privileged -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --userns=keep-id --entrypoint=bash netbrain/zwift 
sudo apt update && sudo apt -y install mesa-utils
glxinfo | egrep "(glx)|(rendering)"
glxgears
exit

# docker
docker run -it --rm --privileged -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  --entrypoint=bash netbrain/zwift 
sudo apt update && sudo apt -y install mesa-utils
glxinfo | egrep "(glx)|(rendering)"
glxgears
exit
```

**Comment by netbrain** [comment]
You might also have to do `xhost +` before running the abovementioned.

**Comment by cjensen506** [comment]
Tried the docker version.

The `glxinfo | egrep "(glx)|(rendering)"` didn't output anything. 

`glxinfo` by itself just outputs: 

user@a294d42ac8a6:~$ glxinfo                            
name of display: :0


And this output from glxgears
user@a294d42ac8a6:~$ glxgears
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  147 ()
  Minor opcode of failed request:  7
  Serial number of failed request:  41
  Current serial number in output stream:  43

**Comment by netbrain** [comment]
Since your using nouveau you might need to add --device /dev/dri:/dev/dri, not sure tho.

**Comment by netbrain** [comment]
But in any case if you can't get proper output from glxinfo or start glxgears, then something is wrong with the system setup. 

What is your docker version? and are you running docker-desktop? There has been other users who had problems when running fedora and docker-desktop. But everything worked when installing the docker-engine

https://docs.docker.com/engine/install/fedora/

**Comment by netbrain** [comment]
--device needs to be at the start, not the end.

**Comment by cjensen506** [comment]
glxinfo seems to just hang on me until after a few minutes I give in and kill it.

```
user@26728f9912e6:~$ glxinfo
name of display: :0
^C
```

Also just to re-iterate. I am perfectly happy using xorg. I would only recommend spending time on this if you think it might be a systemic issue you are interested in.

**Comment by netbrain** [comment]
might have been related to #44 , could you check after the next build?
