### ISSUE TITLE
Zwift failing to update from 1.52.0 to 1.52.2

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#43]
From the github actions log, it seems that the `wine64 start ZwiftLauncher.exe SilentLaunch` results with the following exception.

```
0138:err:ole:CoGetContextToken apartment not initialised
0130:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
0158:err:eventlog:ReportEventW L"Application: ZwiftLauncher.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: exception code c000001d, exception address 00007FB4D57CD01C\n"
wine: Unhandled illegal instruction at address 00007FB4D57CD01C (thread 0158), starting debugger...
```

**Comment by netbrain** [comment]
On second look, it looks like its updating.  need to look into this further.

**Comment by quietvoid** [comment]
It updated fine on my side.

**Comment by netbrain** [comment]
https://github.com/netbrain/zwift/actions/workflows/zwift_updater.yaml

How did you update zwift? And how does it differ from the zwift_updater action?

**Comment by quietvoid** [comment]
I have a script for it: https://github.com/quietvoid/zwift/blob/mod/bin/common.sh#L15
It runs the entrypoint with `update` arg, so it should be the same except with a real XWayland display.

**Comment by netbrain** [comment]
Tried running your scripts on my netbrain/zwift:latest image, but this also failed. not sure why. In any case, it seems a rebuild from scratch will solve this issue, so let's see if it happens again, or if it's some kind of fluke.
