### ISSUE TITLE
Outdated drivers / wine base image

### ISSUE THREAD

**Issue by julian-klode** [netbrain/zwift#44]
I was curious to try this out but the netbrain/wine base image seems to be based on bullseye and doesn't have new enough drivers for my Ryzen 6850U. It also doesn't have a Docker file either, so I can't build my own easily without reverse engineering it. I'd like to start with an ubuntu:mantic base really.

**Comment by netbrain** [comment]
it's based on this: https://github.com/netbrain/dockerfiles/tree/master/wine

Feel free to base it on your own image.

What do you mean by that bullseye don't have drivers for your ryzen card? I was not aware that this was even something to take into consideration.

**Comment by julian-klode** [comment]
The 3D drivers are userspace components shipped by mesa; the ones in bullseye (libgl1-mesa-dri) are far too old to support modern GPUs, after all bullseye is almost EOL by now.

**Comment by quietvoid** [comment]
The container is supposed to be using your host drivers, though.

**Comment by simfu** [comment]
Hello,

I confirm it does not work with my recent GPU (AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics). Mesa version included in `netbrain/wine` is indeed too old.

I managed to get Zwift running by rebuilding an image based on a modified version of `netbrain/wine` in which bullseye is replaced by bookworm.

**Comment by netbrain** [comment]
https://hub.docker.com/layers/netbrain/wine/7.0.0-bookworm/images/sha256-93716a9ea11be31f596a1cf53b0637f3e0eeacf2d32fddbf00d072abdb8a2f31?context=explore

**Comment by netbrain** [comment]
Taking your word for it and upgrading to bookworm :)

**Comment by simfu** [comment]
I've rebuilded your wine docker image by changing bullseye to bookworm in the Dockerfile (two changes)
```
@@ -1,4 +1,4 @@
-FROM debian:bullseye-slim
+FROM debian:bookworm-slim

 ENV NVIDIA_VISIBLE_DEVICES \
         ${NVIDIA_VISIBLE_DEVICES:-all}
@@ -32,7 +32,7 @@
        libgl1-mesa-glx libgl1-mesa-glx:i386 \
        libgl1-mesa-dri libgl1-mesa-dri:i386 && \
        wget -qO - http://dl.winehq.org/wine-builds/winehq.key | apt-key add - && \
-       echo "deb https://dl.winehq.org/wine-builds/debian/ bullseye main" > \
+       echo "deb https://dl.winehq.org/wine-builds/debian/ bookworm main" > \
        /etc/apt/sources.list.d/winehq.list && \
        apt-get update && \
        apt-get -y install --install-recommends winehq-stable && \
```

**Comment by netbrain** [comment]
Ah right, missed that one

**Comment by quietvoid** [comment]
The image build fails at `winetricks --unattended dotnet20 win10` when building from scratch now.

**Comment by netbrain** [comment]
Yes I'm aware, trying to fix it when I have the time 😅

**Comment by julian-klode** [comment]
Sorry for starting this. I also spent 4 hours or so trying to produce an image, but from scratch using a Ubuntu container and Ubuntu's wine package and gave up over similar issues at like 11pm and bought an Apple TV later.

I mean graphics is a lot better on PC in wine but the effort of getting it running and keeping it running is a bit mad.

I think a problem is that the image was past built with wine 7 but now it's wine 8.0.2 or something in the winehq and it may have different bugs causing different winetricks to not work, because you can't pin a specific wine repository state.

Good luck though.

**Comment by netbrain** [comment]
I'm pretty sure I have something very soon. I'll keep you posted

**Comment by netbrain** [comment]
trying a matrix build now to check which combinations of versions that work with the bookworm distro

https://github.com/netbrain/zwift/actions/runs/7133908520/job/19427595768

**Comment by netbrain** [comment]
Also my latest Dockerfile with the same versions as used in bullseye build seems to work on bookworm. Let's see if the github action get's a successfull build! :crossed_fingers:

**Comment by netbrain** [comment]
> I mean graphics is a lot better on PC in wine but the effort of getting it running and keeping it running is a bit mad.

Yeah, that is exactly why i started this project, so it should be a single build to rule them all kind of thing. 

I don't blame you for purchasing a Apple TV ;) but your always welcome to try this again in the future :+1:

**Comment by netbrain** [comment]
https://github.com/netbrain/zwift/actions/runs/7134247593

new run started as the other "failed fast".

Seems that we have a couple that is in the green.

How should we proceed with upgrading? just simply use the latest version combination and cross our fingers that it works? or stay on something we know is stable? (i.e wine 7.0, winetricks 2021, wine-mono 7.0) ?

**Comment by netbrain** [comment]
Build from scratch have now replaced the latest container version
