### ISSUE TITLE
List of versions known to build succesfully using debian bookworm

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#47]
|wine, winetricks,  wine-mono|
|------------------------|
|[zwift_build (8.0.2~bookworm-1, 20210206, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428638927#logs)|
|[zwift_build (8.0.1~bookworm-1, 20210206, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428642799#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20210206, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428646469#logs)|
|[zwift_build (7.0.2~bookworm-1, 20210206, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428648850#logs)|
|[zwift_build (7.0.1~bookworm-1, 20210206, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428652530#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20210206, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7134247593/job/19428656040#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20210825, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439804920#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20220328, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439804177#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20220331, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439803234#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20220411, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439802210#logs)|
|[zwift_build (7.0.0.0~bookworm-1, 20220521, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439801267#logs)|
|[zwift_build (7.0.1~bookworm-1, 20210825, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439800302#logs)|
|[zwift_build (7.0.1~bookworm-1, 20220328, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439799291#logs)|
|[zwift_build (7.0.1~bookworm-1, 20220331, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439798287#logs)|
|[zwift_build (7.0.1~bookworm-1, 20220411, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439797335#logs)|
|[zwift_build (7.0.1~bookworm-1, 20220521, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439796395#logs)|
|[zwift_build (7.0.2~bookworm-1, 20210825, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439795572#logs)|
|[zwift_build (7.0.2~bookworm-1, 20220328, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439794683#logs)|
|[zwift_build (7.0.2~bookworm-1, 20220331, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439793089#logs)|
|[zwift_build (7.0.2~bookworm-1, 20220411, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439792090#logs)|
|[zwift_build (7.0.2~bookworm-1, 20220521, 7.0.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439791161#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20210825, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439790793#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20220328, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439789708#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20220331, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439788735#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20220411, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439787982#logs)|
|[zwift_build (8.0.0.0~bookworm-1, 20220521, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439787179#logs)|
|[zwift_build (8.0.1~bookworm-1, 20210825, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439786302#logs)|
|[zwift_build (8.0.1~bookworm-1, 20220328, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439785432#logs)|
|[zwift_build (8.0.1~bookworm-1, 20220331, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439784518#logs)|
|[zwift_build (8.0.1~bookworm-1, 20220411, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439783763#logs)|
|[zwift_build (8.0.1~bookworm-1, 20220521, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439782870#logs)|
|[zwift_build (8.0.2~bookworm-1, 20210825, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439782010#logs)|
|[zwift_build (8.0.2~bookworm-1, 20220328, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439781176#logs)|
|[zwift_build (8.0.2~bookworm-1, 20220331, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439780376#logs)|
|[zwift_build (8.0.2~bookworm-1, 20220411, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439779499#logs)|
|[zwift_build (8.0.2~bookworm-1, 20220521, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439777751#logs)|

**Comment by quietvoid** [comment]
It's a bit weird that the mono version matters considering winetricks is supposed to uninstall it.

Anyways, I've made it work with the latest versions of wine/winetricks in an ArchLinux image as well.
As long as wine-mono 7.4 is installed first.
Need to test a bit more.

**Comment by netbrain** [comment]
Yeah, I don't know why this is the case.

Would be interesting to see how different distros stack up on the compatibility list of versions here. Maybe we should make a dockerfile per distro kind of thing?

The best outcome here would be if we could statically compile wine and have it run zwift and create a minimal image. But i doubt that would work, too many system dependencies i think.

I'm also eager to test a nix container of this to see if we can further improve this in terms of compatibility/container size or any other factors for that matter.

**Comment by netbrain** [comment]
seems this is the latest version that will build on debian bookworm
[zwift_build (8.0.2~bookworm-1, 20220521, 7.4.0)](https://github.com/netbrain/zwift/actions/runs/7138354313/job/19439777751#logs)

**Comment by quietvoid** [comment]
The basics seem to be that `dotnet20` and `d3dcompiler_47` aren't necessary anymore.
Installing `dotnet48` after `wine-mono` version `8.1.0` works fine, with manual intervention for some errors that don't break setup.

My image based on Arch is around ~4GB smaller, probably because there are less dependencies.

**Comment by netbrain** [comment]
I've implemented your suggestions and also added a winetricks zwift verb. Would you mind taking a look at it?

https://github.com/netbrain/zwift/pull/50

**Comment by netbrain** [comment]
Can also confirm that we get about a size reduction with this change.
```
netbrain/zwift                                          1.54.0        0b973b171209   8 hours ago    11.9GB
netbrain/zwift                                          latest        f6c54d2d9b23   6 days ago     13.3GB
```

The 1.54.0 is the newly built image using #50 while the other is pulled from docker hub.

Not sure what the gzipped size will be after push to docker hub tho.

**Comment by netbrain** [comment]
4.71 GB when  pushed to docker hub, pretty nice, if i may say so myself :)

**Comment by quietvoid** [comment]
FYI with the latest `winetricks` version `20240105`, the `games` category was removed.
So it needs to be replaced by `apps` in the verb file.

**Comment by netbrain** [comment]
https://github.com/netbrain/zwift/pull/69

Like this?

**Comment by quietvoid** [comment]
> https://github.com/netbrain/zwift/pull/69
> 
> Like this?

Yes but I didn't test if `apps` works with thr currently used version.
