### ISSUE TITLE
[Question] Possible to get Bluetooth to work?

### ISSUE THREAD

**Issue by ludberg** [netbrain/zwift#5]
I am so happy I found this! Big thanks!

Would it be possible to get Bluetooth to work, so we're not dependent on the Companion app for HR/Power?

**Comment by netbrain** [comment]
Maybe, but i don't know how. You need to get wine to recognize the ant+ or
bt device and then you need Zwift itself to do the same. I think it's
possible, but probably not in wine's current state.
