### ISSUE TITLE
Nvidia Cards / Arch Linux - CPU is used

### ISSUE THREAD

**Issue by cmuench** [netbrain/zwift#53]
Hi,

I had the issue that my NVIDIA GeForce RTX 4060 Ti with installed proprietary dirver was detected but the CPU was still used.
So I searched for a solution.
Adding the  `-e NVIDIA_DRIVER_CAPABILITIES=all` to the docker run command solved the issue on my machine.
Maybe this could also help other Linux Zwifters :-)

**Comment by netbrain** [comment]
Could maybe make this the default value in the Dockerfile...

**Comment by netbrain** [comment]
On the next build from scratch this should be the default value as per change in 69065b1564aca27741bdaabefef367c1a7f59558
