### ISSUE TITLE
Zwift is not stating

### ISSUE THREAD

**Issue by HeavyD2k** [netbrain/zwift#57]
I installed docker on ubuntu and when starting zwift (sudo zwift) its not starting
See the terminal output

+ IMAGE=docker.io/netbrain/zwift
+ VERSION=latest
+ [[ ! -n '' ]]
++ command -v podman
+ [[ -x '' ]]
+ CONTAINER_TOOL=docker
+ [[ ! -n '' ]]
+ docker pull docker.io/netbrain/zwift:latest
latest: Pulling from netbrain/zwift
Digest: sha256:b530163c2430b87a3b74087226be7b4dfa53166331246bde36e460f42934956f
Status: Image is up to date for netbrain/zwift:latest
docker.io/netbrain/zwift:latest
+ [[ -f /proc/driver/nvidia/version ]]
+ VGA_DEVICE_FLAG='--device /dev/dri:/dev/dri'
+++ '[' docker = podman ']'
++ docker run -d --rm --privileged -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/0/pulse:/run/user/1000/pulse -v zwift-root:/home/user/Zwift --device /dev/dri:/dev/dri docker.io/netbrain/zwift:latest
+ CONTAINER=bc495a799fb0d4f56839af516edf605f33e10e521e414a5f92aff67edad63ce8
+ [[ -z '' ]]
++ docker inspect '--format={{ .Config.Hostname  }}' bc495a799fb0d4f56839af516edf605f33e10e521e414a5f92aff67edad63ce8
+ xhost +local:bc495a799fb0
non-network local connections being added to access control list

Have you anny idea what in can be?

Thank you

**Comment by netbrain** [comment]
Maybe try this? https://github.com/netbrain/zwift/issues/54#issuecomment-1877155180

**Comment by HeavyD2k** [comment]
i have Intel/AMD video card combo :(

**Comment by netbrain** [comment]
If you can't get GPU passthrough to work you could always try to just install Zwift on the host machine instead. You need to install wine and winetricks, and then you should be able to run winetricks zwift.verb.

Take a look in the entrypoint and dockerfile for details

**Comment by HeavyD2k** [comment]
Hello, will try the pass-trough
I tried also Wine and Lutris+wine

Lutris errors :D

ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

And simple wine instalation including .net and web-view that wine mono is missing :) in condition that i have .net already installed :dagger: 


it seams that Zwit is a hard nut to crack....

**Comment by netbrain** [comment]
Yes, that's why I combined it with containers to make it more reliable across several systems.

Still not perfect tho.
