### ISSUE TITLE
Can Zwift run in maximized windows ?

### ISSUE THREAD

**Issue by MailFranzel** [netbrain/zwift#58]
I use Fedora with two HD monitors. Zwift runs on one monitor in the window. 
However, this window is not as big as the screen. I still have to make it a "fullscreen window". Can I tell Docker to run Zwift in a maximized window?

**Comment by gallais** [comment]
Once you're logged in, you can go to the settings and pick the fullscreen option.

Click on your avatar (in the top bar) > My settings > Sound & Display tab > Screen Mode

**Comment by MailFranzel** [comment]
Thanks a lot! When I do this: Zwift opens as fullscreen; but when I use the second monitor the fullscreen-zwift is close to the taskbar. I can open it again, but it is not the I want. I think I need a maximized windows, no fullscreen windows for zwift.

**Comment by quietvoid** [comment]
Sounds like something your window manager should be handling.
Maybe look up docs for your desktop environment.

**Comment by netbrain** [comment]
Closing as this is definitely a window manager issue.
