### ISSUE TITLE
Problem with companion app

### ISSUE THREAD

**Issue by atoy40** [netbrain/zwift#67]
Hi,

I'm trying to setup the companion app to bridge my connected trainer.
When I launch zwift, I can see the bluetooth device, and connect to it, but as soon as I live the "devices window" and go on the riding interface, the "watt" becomme grey and it indicate the device is not available. I soon as I reopen the device windows, the powermeter and resistance device reconnect immediatly.... But disconnect again as soon as I close it.

Anyone having the same problem ??

thanks
Anthony.

**Comment by netbrain** [comment]
This is probably not an issue regarding Linux and Zwift, probably a general android/Zwift connectivity issue.

Unless you can state that the bridge solution works with the windows version or some other platform. Then this is not the right place for this issue I'm afraid.
