### ISSUE TITLE
Zwift is crashing during workout

### ISSUE THREAD

**Issue by wastlh** [netbrain/zwift#72]
After 20-30 minutes of riding a workout, Zwift is freezing and would crash. 

**To Reproduce**
1. Start Zwift via Docker
2. Start a workout
3. Ride for about 20-30 min
4. Zwift freezes, and after a minute crashes finally. 

**Expected behavior**
Expected behavior would be no freeze or crashing. 

**Screenshots**
No screenshots available. 

**Additional context**
I have a relatively new laptop with TuxedoOS (based on Ubuntu 23.10).

**Comment by quietvoid** [comment]
You might need to disable video screenshots.

**Comment by wastlh** [comment]
Will try that and give feedback after a couple of tests. Thanks for the help though!

**Comment by henningf3** [comment]
See #26 as well
