### ISSUE TITLE
[HELP] Zwift does not have write access to Download and Documents folder

### ISSUE THREAD

**Issue by peterpedron** [netbrain/zwift#74]
**Host information**
> i.e ùname -a`

Linux myubuntu 5.15.0-94-generic #104~20.04.1-Ubuntu SMP Tue Jan 16 13:34:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Container information**
> i.e `docker --version`

Docker version 25.0.3, build 4debf41

**Hardware information**
> i.e `lspci | egrep -i "(vga|3d)"`

00:17.0 SATA controller: Intel Corporation Device 43d3 (rev 11)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1fbc (rev a1)

## Issue details
Fresh docker installation. When running zwift with no further configuration (no custom volume etc.) I get a wine popup saying:
![image](https://github.com/netbrain/zwift/assets/3693909/ebf37da7-e832-4af1-9f2f-9b2c842098d1)

Nothing further happens, the container keeps on running, but without any graphical output.

Output of zwift command:
```
+ IMAGE=docker.io/netbrain/zwift
+ VERSION=latest
+ [[ ! -n '' ]]
++ command -v podman
+ [[ -x '' ]]
+ CONTAINER_TOOL=docker
+ [[ ! -n '' ]]
+ docker pull docker.io/netbrain/zwift:latest
latest: Pulling from netbrain/zwift
Digest: sha256:cf86bf96337b9d43e97c47bef19128801e45c2d9c47753fc8e370718343f9ad3
Status: Image is up to date for netbrain/zwift:latest
docker.io/netbrain/zwift:latest
+ [[ -f /proc/driver/nvidia/version ]]
+ VGA_DEVICE_FLAG='--gpus all'
+++ '[' docker = podman ']'
++ docker run -d --rm --privileged -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/785946/pulse:/run/user/1000/pulse -v zwift-user:/home/user/Zwift --gpus all docker.io/netbrain/zwift:latest
+ CONTAINER=403591d99c0118f1650e3e478554356ab6747956e3134ae63ed1dcb2d5fe6e46
+ [[ -z '' ]]
++ docker inspect '--format={{ .Config.Hostname  }}' 403591d99c0118f1650e3e478554356ab6747956e3134ae63ed1dcb2d5fe6e46
+ xhost +local:403591d99c01
non-network local connections being added to access control list
```

**Comment by quietvoid** [comment]
See https://github.com/netbrain/zwift/issues/56#issuecomment-1913116407.
Clearly the previous issue shouldn't have been closed.
