### ISSUE TITLE
Tried a ride twice, froze and crashed both times as I was getting an award.

### ISSUE THREAD

**Issue by joekm** [netbrain/zwift#75]
**Describe the bug**
Tried a ride twice, froze and crashed both times as I was getting an award.  Using the Zwift companion app with it.

**To Reproduce**
Start ride
Wait until some "award notification" shows (I.E.  "You've unlocked the Zwift Glasses"
Game freezes....eventually crashes to terminal.

**Expected behavior**
Able to finish and save ride.

**Screenshots**
N/A

**Additional context**
Running EndeavourOS  All AMD setup.

**Comment by joekm** [comment]
I've switched from "fullscreen" to "windowed" mode.  I'll try again tomorrow running it that way and see if I have better luck.  I don't suppose there's a setting to run gamemode with this?  That might help as well.

**Comment by quietvoid** [comment]
Did you try disabling video screenshots?

**Comment by joekm** [comment]
No but, I will.  Is that a known fix?

**Comment by quietvoid** [comment]
Yes, crashes are common with the setting enabled.
See https://github.com/netbrain/zwift/issues/26.

**Comment by joekm** [comment]
Ok, I've the video back to fullscreen and disabled video screenshots.  There's also an auto upload screenshots, but I think that happens after the ride is saved anyways so it shouldn't matter.  Nonetheless, I'll set that to "never" for now as well.

**Comment by joekm** [comment]
My system by the way....
![image](https://github.com/netbrain/zwift/assets/4186241/d9f6b685-eba5-4742-ad5e-228d3c4636eb)

**Comment by quietvoid** [comment]
I run Zwift on a similar setup. Sway with CPU 5900X, GPU 6900 XT.
I haven't done a ride on Zwift 1.59.0 but no issues otherwise, so it's probably caused by video screenshots.

**Comment by netbrain** [comment]
@joekm please close the issue if it's resolved.

**Comment by joekm** [comment]
Forgot to check the memory useage during but, got in a 34+ minute ride, well past where I normally crash, and no issues.  I also use OpenRGB to give me feedback on CPU, GPU, and nVMe temps.   All stayed  in pretty nominal ranges.  CPU got the warmest but, well below any concern.

I'd say I'm rollin'  :)  Thanks for the help everyone.

**Comment by dmccombs** [comment]
I was coming to suggest adding a note to the README about disabling video screenshots after having run into this myself - I'm glad to see it was added in commit https://github.com/netbrain/zwift/commit/24ac8264fb99dbd52399022d478bb3ac72ab1cd8 - thanks!

**Comment by perrin4869** [comment]
I've been experiencing this issue for about a week, crashing at around the 35min mark. I am also running a radeon card, 6800XT. As far as I can see, everyone who reported this error seems to be on radeon, is there a chance this is a radeon specific issue, or did someone on nvidia also have this problem? Just out of curiosity

**Comment by netbrain** [comment]
Video screenshots most likely. Disable them in settings

**Comment by dmccombs** [comment]
@perrin4869 I have an Nvidia GPU and have this same problem with video screenshots crashing Zwift in Linux - all is well so long as those are disabled.
