### ISSUE TITLE
Using ant+ via the companion app

### ISSUE THREAD

**Issue by perrin4869** [netbrain/zwift#77]
The README suggests that you could pair an ant+ sensor via the companion app. Also, the [comment here](https://github.com/netbrain/zwift/issues/2#issuecomment-1067238620) also suggests the same.
However, I didn't have any luck using an ANT+ dongle on my android phone as [suggested here](https://forums.zwift.com/t/ant-heart-rate-monitors/169767) (I think this only works with the android version of the Zwift, not the companion?), and [this post](https://forums.zwift.com/t/connect-to-ant-through-phone-on-zwift-companion-and-upcoming-zwift-android-app/13362/7) suggests that ant+ is also not supported via the companion app.
Was wondering which is correct, and if it's possible, how to connect an ANT+ HRM to Zwift? Thanks!

**Comment by netbrain** [comment]
I don't think ant+ works with the companion app. Probably just a minor flaw in the README

**Comment by perrin4869** [comment]
gotcha! thanks for the clarification!
