### ISSUE TITLE
No access to Documents / Downloads folder when launching zwift

### ISSUE THREAD

**Issue by pierretamisier** [netbrain/zwift#79]
Greetings,

Running into issues running `zwift`.

```
pierre@thinkpad:~/Downloads$ uname -a
Linux thinkpad 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
pierre@thinkpad:~/Downloads$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
pierre@thinkpad:~/Downloads$ lspci | egrep -i "(vga|3d)"
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
```

## Issue details
I tried to open the dockerized zwift by doing `zwift` or `sudo zwift` and it both cases I receive the following errors messages in 2 distict popus that disappear automatically after a second or two.

> There was an error accessing your Documents folder. There was also an error trying to create a Zwift folder on your desktop as a fall-back. This means Zwift can't save any files. Please contact Zwift support.

> Zwift is unable to write to the Downloads folder. Check folder permissions. If the problem persists, contact Zwift support with error code ZL07. Would you like to go to the Zwift Support Page now?

**Comment by quietvoid** [comment]
See https://github.com/netbrain/zwift/issues/56#issuecomment-1913116407

**Comment by pierretamisier** [comment]
Cheers thanks!
