### ISSUE TITLE
Fix the "How can I add custom .zwo files?" section in the README

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#89]
Improve this section in the README and check if it is currently correct.

Simplify if possible.

**Comment by netbrain** [comment]
@jonathanglima :point_up:  not sure if the latest wine 9 has broken this for you. But i think the paths may be incorrect now. And maybe this could be simplified to allow for a separate volume for zwo files. Depends on where the zwo files are located.

**Comment by sHedC** [comment]
Would doing a script to add or make an option for zwift to make use of that to copy or add a zwo mount point?  then get the id from the auth and do a link or sync from the mount point to the Workouts?

e.g.  `ZWIFT_ZWO=/home/<user>/.config/Zwift/Workouts zwift`
or just use the config area to say if exists Workouts then mount to copy/ link?

Looking up the ID from the login details is as follows.
`curl -sSl --get --data-urlencode "username=user" --data-urlencode "pw=password" https://z00pbp8lig.execute-api.us-west-1.amazonaws.com/latest/zwiftId`

Thoughts?

**Comment by netbrain** [comment]
Probably better if we provide a way to find your Zwift Id as a helper script or just in the docs and then have two env vars.

ZWIFT_ZWO=/home/netbrain/my-zwo
ZWIFT_ACCOUNT_ID=1234

With these two we can link or copy the files into the container. Preferably link, but then you must link with proper uid/gid.

**Comment by netbrain** [comment]
I try to follow KISS (keep it simple stupid) whenever possible

**Comment by sHedC** [comment]
Added Support in latest, see the README.
