### ISSUE TITLE
Missing documents folder

### ISSUE THREAD

**Issue by eskimos20** [netbrain/zwift#9]
Hi! 

Ive tried to get this started and all seems well. But when zwift is about to start it complains about missing Documents folder. 

I have tried a newly installed Ubuntu 22.04 both with english and swedish language. I thought it might be looking for "Documents" and in swedish the name is "Dokument". I tried creating Documents folders everywhere to solve this and also create a zwift folder on Desktop just in case. 

![20221111_181957](https://user-images.githubusercontent.com/33683145/201459903-bb5707f9-ede4-4ab2-84b2-508c77108079.jpg)

**Comment by carlohamalainen** [comment]
The container uses ``$HOME/.zwift/$USER`` for the home directory volume; can you check that on your PC? You're using sudo so it might be looking for ``/root/.zwift/root`` ?

Try running the ``zwift.sh`` script with these two ``set`` lines so we can see what it's trying to do:

```
#!/bin/bash

set -e # add this
set -x # add this

# The home directory to store zwift data
ZWIFT_HOME=${ZWIFT_HOME:-$HOME/.zwift/$USER}

(rest of the file)
```

**Comment by eskimos20** [comment]
Its trying to create the following. And when I look in the folders it seems as it has created everything.

**Comment by eskimos20** [comment]
Found out that this was already handled in an closed issue. I will try set my folder with chmod 1000.

**Comment by netbrain** [comment]
For future reference, zwift.sh should never be sudo'ed.

**Comment by eskimos20** [comment]
Worked like a charm now. 

I had missed that docker should not be runned as sudo aswell as the script itself. 

Thanks a lot for this :)

**Comment by bigbuka** [comment]
Thanks for pointing me to the solution.  I also had to run "sudo usermod -aG docker $USER" then restart my pc.  After that it worked like a charm!  Thanks so much for getting Zwift to us linux users! :-D

**Comment by fgebhart** [comment]
Another one for future reference: I had to run
```
# get path to mountpoint
docker volume inspect zwift-$USER
```
Copy the value associated with the key `Mountpoint`. For me this was `/var/lib/docker/volumes/zwift-myuser/_data`.
And then:
```
# change the owner of this mountpoint path to your current user
sudo chown -R myuser:myuser  /var/lib/docker/volumes/zwift-myuser/_data
```
Followed by:
```
zwift
```

Hope that helps!
