### ISSUE TITLE
[HELP] With latest update, Zwift no longer launches.

### ISSUE THREAD

**Issue by joekm** [netbrain/zwift#97]
**Host information**
Linux jkmooney-ms7c96 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux

**Container information**
podman version 5.0.2

**Hardware information**
25:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] (rev c5)

## Issue details
Haven't used it in a few weeks.  When launching it, it went through a sizeable updates then just stops at the command prompt without launching.  Running btop shows Zwift is not running in background.    Not getting any error messages that I can see (running Wayland session with Hyprland desktop).  It just doesn't seem to be launching.

Last few lines of launch messages are below:

Copying config 38c46bfce7 done   | 
Writing manifest to image destination
38c46bfce73df336a430af4edb4e2b1993d82fa7e76b7e674b02be986db9faf4
+++ '[' podman = podman ']'
+++ echo --userns=keep-id
++ podman run -d --rm --privileged --network bridge --name zwift-jkmooney -e DISPLAY=:1 -e ZWIFT_UID=1000 -e ZWIFT_GID=1000 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/1000/pulse:/run/user/1000/pulse -v zwift-jkmooney:/home/user/.wine/drive_c/users/user/Documents/Zwift --userns=keep-id --device /dev/dri:/dev/dri docker.io/netbrain/zwift:latest
+ CONTAINER=dad53a16c4241cc9b30edb4f4369d66e9aa0aa04294807d834f6e29da8769657
+ [[ -z wayland-1 ]]

**Comment by joekm** [comment]
Ok, looking through the logs, it appears it cold be a permission thing?

This snippet seems to be it

Apr 24 22:07:53 jkmooney-ms7c96 zwift-jkmooney[3709]: + groupmod -o -g 1000 user
Apr 24 22:07:53 jkmooney-ms7c96 zwift-jkmooney[3709]: groupmod: Permission denied.
Apr 24 22:07:53 jkmooney-ms7c96 zwift-jkmooney[3709]: groupmod: cannot lock /etc/group; try again later.
Apr 24 22:07:53 jkmooney-ms7c96 conmon[3709]: conmon 2aefc04b45fa742c51ff <nwarn>: Failed to open cgroups file: /s>

I can post the entire output if that might help but, it appears a file is not opening for lack of permission.

**Comment by netbrain** [comment]
Related to #94

**Comment by gallais** [comment]
@joekm In the meantime you should be able to use the `VERSION` environment variable to boot the old image.
Don't know what version you were using but e.g. `VERSION=1.60.0 zwift` should still work.

**Comment by joekm** [comment]
Going to VERSION=1.60.0 still doesn't launch in Hyprland (Wayland) but, fortunately, seems to be working with XFCE (XOrg).   So, I'm "up and running" again.   Thanks :)
